language: clojure
lein: lein2
script:
  - lein2 build-site
after_success:
  - build/travis-publish-gh-page.sh
env:
  global:
    secure: "LebgqWMz930ET4y98qyusP5HpJ+0D42nU0IW1IvBFKAA+8GQ8GDkgotYFkaY1I0rlGS8o+MINTJnCKLp+1PshzLvRJ7DLWLRLa2AoU12wD7FOeg8mKGqHVlNT1Th3e0WgmMsQLqNnyiCJYMLQAeaZ/qUuA68FkLVs08IvCJSvnA="
